blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/medik8s/.github/security/advisories/new
    about: Report a security vulnerability privately via GitHub Security Advisory
  - name: Mailing list
    url: https://groups.google.com/g/medik8s
    about: Ask questions or start a discussion on the medik8s mailing list
  - name: Website
    url: https://www.medik8s.io
    about: Learn more about the medik8s project
